# Generated by Django 4.2.8 on 2023-12-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GraderApp', '0002_alter_assignment_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='question',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
