# Generated by Django 4.2.8 on 2023-12-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GraderApp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubric',
            old_name='marks',
            new_name='max_marks',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='question',
        ),
        migrations.AddField(
            model_name='rubric',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GraderApp.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
