# Generated by Django 4.1.3 on 2024-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0002_question_alter_user_first_name_questionsinassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsinassignment",
            name="marks",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
